[project]
name = "reconn-wave-power"
version = "0.1.0"
description = "Tools to compute wave power spectra from hybrid simulations (electric and magnetic fields)"
authors = [{name = "Colby Haggerty", email = "colbyh@hawaii.edu"}]
dependencies = [
  "numpy>=1.23",
  "scipy>=1.9",
  "xarray>=2022.3",
  "dask>=2022.2 ; extra == 'dask'",
  "imageio-ffmpeg>=0.4 ; extra == 'movies'",
  "matplotlib>=3.5",
  "pandas>=1.4",
  "tqdm>=4.60",
  "h5py>=3.0",
  "dhybridrpy"
]
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
